services:
  app:
    build:
      context: .
    env_file:
      - prod.env
    restart: always
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
    name: chatbot-network
